version: '3.2'
services:
  sonarqube:
    build:
      context: sonarqube/
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /tmp/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube
# ------------------------------------------------------------------------------
# admin password : adminpassword@@
# docker run --rm httpd:2.4-alpine htpasswd -nbB admin 'adminpassword@@' | cut -d ":" -f 2
# https://gist.github.com/deviantony/62c009b41bde5e078b1a7de9f11f5e55
#------------------------------------------------------------------------------
  portainer:
    image: portainer/portainer:linux-amd64-1.21.0
    container_name: portainer
    command: --admin-password '$$2y$$05$$.dARPJyZ9jJIDPhn05eW9eAUhJhaKQE1djkhmLSkQEFRN8WGuh2MS'
    restart: always
    ports:
      - 8000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
# ------------------------------------------------------------------------------
# DOCUMENTATION SECTION
#------------------------------------------------------------------------------
  wiki:
    image: mediawiki
    #restart: always
    links:
      - db
    ports:
      - "8001:80"
    volumes:
      - ./images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
  db:
    image: mariadb
    #restart: always
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wiki_user
      MYSQL_PASSWORD: wiki_password
      MYSQL_ROOT_PASSWORD: mariadb_secret
    # fix for volume issues on Docker for Windows
    command: mysqld --innodb-flush-method=fsync
    volumes:
      - ./db:/var/lib/mysql
